name: 'Deploy to Development'

on:
  push:

jobs:
  deploy-to-development:
    name: 'Deploy to Development'
    runs-on: ubuntu-latest
    environment: development
    env:
      TF_WORKSPACE: cross-project--routing-infrastructure-dev

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -recursive

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Generate Terravision Diagrams
      uses: JK-Chung/terravision-actions-s3-deploy@v0.0-alpha
      with:
        aws-access-key-id: AKIA3O5G5ORPLFTQYAGE
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_AKIA3O5G5ORPLFTQYAGE }}
        aws-s3-bucket-region: eu-west-1
        aws-s3-bucket-base-uri: s3://terravision-demo-static-site/terravision-artifacts
